CREATE SEQUENCE STUDENT_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE FUNCTION GEN_ID(
    ADMISSION_DATE DATE,
    DEPT CHAR,
    PROGRAM CHAR,
    SECTION CHAR
) RETURN VARCHAR2 IS
    YEAR_PART VARCHAR2(2);
    NEXT_SEQ  VARCHAR2(2);
BEGIN
    YEAR_PART := TO_CHAR(ADMISSION_DATE, 'YY');
    NEXT_SEQ := LPAD(TO_CHAR(NEXTVAL('student_id_seq')), 2, '0');
    RETURN YEAR_PART
           || '00'
           || DEPT
           || PROGRAM
           || SECTION
           || NEXT_SEQ;
END;
/

CREATE TABLE STUDENT (
    ID VARCHAR2(12) PRIMARY KEY,
    DATE_OF_ADMISSION DATE,
    DEPARTMENT CHAR(1) CHECK (DEPARTMENT IN ('1', '2', '3', '4', '5', '6')),
    PROGRAM CHAR(1) CHECK (PROGRAM IN ('1', '2', '3', '4', '5', '6')),
    SECTION CHAR(1) CHECK (SECTION IN ('1', '2', '3', '4', '5', '6'))
);

CREATE OR REPLACE TRIGGER BEFORE_INSERT_STUDENT BEFORE
    INSERT ON STUDENT FOR EACH ROW
BEGIN
    :NEW.ID := GEN_ID(:NEW.DATE_OF_ADMISSION, :NEW.DEPARTMENT, :NEW.PROGRAM, :NEW.SECTION);
END;
/