CREATE TABLE CUSTOMER(
    SSN INT PRIMARY KEY,
    NAME VARCHAR2(20),
    SURNAME VARCHAR2(20),
    PHONENUM NUMBER(11, 0),
    PLAN INT
);

CREATE TABLE PRICINGPLAN(
    CODE INT PRIMARY KEY,
    CONNECTIONFEE DECIMAL(5, 2),
    PRICEPERSECOND DECIMAL(5, 2)
);

CREATE TABLE PHONECALL(
    SSN INT,
    TIME DATE,
    CALLEDNUMBER NUMBER(11, 0),
    SECONDS INT,
    PRIMARY KEY (SSN, TIME)
);

CREATE TABLE BILL(
    SSN INT,
    MONTH INT,
    YEAR INT,
    AMOUNT NUMBER(10, 2),
    PRIMARY KEY (SSN, MONTH, YEAR)
);

INSERT INTO CUSTOMER (
    SSN,
    NAME,
    SURNAME,
    PHONENUM,
    PLAN
) VALUES (
    1,
    'Rahim',
    'Ahmed',
    01711000001,
    1
);

INSERT INTO CUSTOMER (
    SSN,
    NAME,
    SURNAME,
    PHONENUM,
    PLAN
) VALUES (
    2,
    'Karim',
    'Islam',
    01711000002,
    2
);

INSERT INTO CUSTOMER (
    SSN,
    NAME,
    SURNAME,
    PHONENUM,
    PLAN
) VALUES (
    3,
    'Fatema',
    'Begum',
    01711000003,
    3
);

INSERT INTO CUSTOMER (
    SSN,
    NAME,
    SURNAME,
    PHONENUM,
    PLAN
) VALUES (
    4,
    'Rashed',
    'Khan',
    01711000004,
    1
);

INSERT INTO CUSTOMER (
    SSN,
    NAME,
    SURNAME,
    PHONENUM,
    PLAN
) VALUES (
    5,
    'Mina',
    'Sultana',
    01711000005,
    2
);

INSERT INTO PRICINGPLAN (
    CODE,
    CONNECTIONFEE,
    PRICEPERSECOND
) VALUES (
    1,
    50.00,
    0.50
);

INSERT INTO PRICINGPLAN (
    CODE,
    CONNECTIONFEE,
    PRICEPERSECOND
) VALUES (
    2,
    100.00,
    0.30
);

INSERT INTO PRICINGPLAN (
    CODE,
    CONNECTIONFEE,
    PRICEPERSECOND
) VALUES (
    3,
    150.00,
    0.20
);

INSERT INTO PHONECALL (
    SSN,
    TIME,
    CALLEDNUMBER,
    SECONDS
) VALUES (
    1,
    TO_DATE('2024-10-01 09:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    8801611000011,
    180
);

INSERT INTO PHONECALL (
    SSN,
    TIME,
    CALLEDNUMBER,
    SECONDS
) VALUES (
    2,
    TO_DATE('2024-10-01 12:45:00', 'YYYY-MM-DD HH24:MI:SS'),
    8801611000012,
    240
);

INSERT INTO PHONECALL (
    SSN,
    TIME,
    CALLEDNUMBER,
    SECONDS
) VALUES (
    3,
    TO_DATE('2024-10-02 15:15:00', 'YYYY-MM-DD HH24:MI:SS'),
    8801611000013,
    300
);

INSERT INTO PHONECALL (
    SSN,
    TIME,
    CALLEDNUMBER,
    SECONDS
) VALUES (
    4,
    TO_DATE('2024-10-03 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    8801611000014,
    120
);

INSERT INTO PHONECALL (
    SSN,
    TIME,
    CALLEDNUMBER,
    SECONDS
) VALUES (
    5,
    TO_DATE('2024-10-04 20:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    8801611000015,
    600
);

CREATE OR REPLACE TRIGGER INITIATION AFTER
    INSERT ON CUSTOMER FOR EACH ROW
BEGIN
    INSERT INTO BILL (
        SSN,
        MONTH,
        YEAR,
        AMOUNT
    ) VALUES (
        :NEW.SSN,
        EXTRACT(MONTH FROM SYSDATE),
        EXTRACT(YEAR FROM SYSDATE),
        0
    );
END;
/

CREATE OR REPLACE TRIGGER BILLING AFTER
    INSERT ON PHONECALL FOR EACH ROW
DECLARE
    V_PLAN           INT;
    V_CONNECTIONFEE  DECIMAL(5, 2);
    V_PRICEPERSECOND DECIMAL(5, 2);
    V_AMOUNT         DECIMAL(10, 2);
BEGIN
    SELECT
        PLAN INTO V_PLAN
    FROM
        CUSTOMER
    WHERE
        SSN = :NEW.SSN;
    SELECT
        CONNECTIONFEE,
        PRICEPERSECOND INTO V_CONNECTIONFEE,
        V_PRICEPERSECOND
    FROM
        PRICINGPLAN
    WHERE
        CODE = V_PLAN;
    V_AMOUNT := V_PRICEPERSECOND * :NEW.SECONDS;
    UPDATE BILL
    SET
        AMOUNT = AMOUNT + V_AMOUNT
    WHERE
        SSN = :NEW.SSN
        AND MONTH = EXTRACT(MONTH FROM :NEW.TIME)
        AND YEAR = EXTRACT(YEAR FROM :NEW.TIME);
END;